# Author: Nachat Kaewmeesang
# This code is used for internship for Vanness Plus Consulting Co., Ltd
# compose.yaml sets up 3 container services for the webapp
# - mysql -> user='root' password='' port=3306
# - fastapi-app -> port=8000; you can check docs via localhost:8000/docs
# - svelte-app -> port=5173
# Simply start your docker engine and run `docker compose up`

services:
  svelte-app:
    build: 
      context: ./frontend  # Build the image from frontend
      args: 
        - --no-cache=True
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/svelte.config.js:/app/svelte.config.js
      - ./frontend/.svelte-kit:/app/.svelte-kit
    ports:
      - "5173:5173"  # Map container port 5173 (default Vite port)
    depends_on:
      - fastapi-app  # Wait for backend to start before running the FastAPI app
    command: npm run dev -- --host 0.0.0.0 --port 5173
  fastapi-app:
    build: 
      context: ./backend  # Build the image from backend
      args: 
        - --no-cache=True
    volumes:
      - "./backend:/app"  # Mount current directory to /app in the container
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    depends_on:
      - mysql  # Wait for MySQL to start before running the FastAPI app
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mysql'
      # In this case, login with "root", password=""
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - sqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  sqldata: